---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    env: demo
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh','-c', 'echo the app is running && sleep 3600']   # Command and Arguments are passed in a single line
      env:
        - name: FIRSTNAME   # Environment variables
          value: "ritesh"
        - name: LASTNAME
          value: "nayak"
  
    - name: mydb-container
      image: redis

  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh' , '-c']  # Command is passed
      args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done']  # Argument is passed
    # Second init container which will wait until it is able to get response from nslookup mydb service
    - name: init-mydb
      image: busybox:1.28
      command: ['sh' , '-c']  # Command is passed
      args: ['until nslookup mydb.default.svc.cluster.local; do echo waiting for service to be up; sleep 2; done']

