---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ns2
  namespace: ns2
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
        run: nginx
      name: nginx
      
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      
      run: nginx