---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    env: dev
spec:
  template:
    metadata:
      labels:
        env: dev
    name: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:1.23.4-alpine
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 1
  selector:
    matchLabels:
      env: dev