---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
  labels:
    env: demo
    svc: clusterIP
spec:
  type: ClusterIp # Even if type is not specified here, k8s by default creates a ClusterIp
  ports:
   - port: 80
     targetPort: 80
  selector:
      env: demo 