# Create a service and expose the application on port 80 outside with a nodeport 30001
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    svc: nodeport
    env: demo
# Inside spec we'll specify what type of service it is against the type attribute.
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
  selector:
      env: demo   # This helps the service to be tagged to the right pods which has label as env:demo
