apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - image: redis
    name: redis
